name: Release

on:
  push:
    tags:
      - "release/**"

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - run: "bun install"
      - run: "bun -v"
